
import React from "react";

const ReportFooter = () => {
  return (
    <div className="text-sm text-gray-500 mt-10 border-t pt-4 print:mt-4 print:pt-2">
      <p>This report is generated by DyslexAI as a preliminary screening tool and is not a formal diagnosis. For a comprehensive evaluation, please consult with a qualified educational psychologist or specialist.</p>
      <p className="mt-1">© {new Date().getFullYear()} DyslexAI - All Rights Reserved</p>
    </div>
  );
};

export default ReportFooter;
